# mkdocs.yml
site_name: MDSNews
site_url: https://camshron.github.io/mdsnews/ # Remember to replace 'your-username'

theme:
  name: material
  font:
    # Benton Sans is a commercial font. If you have it installed on your system
    # and users also have it, it might work.
    # For wider compatibility, consider a visually similar Google Font as a fallback.
    # Material for MkDocs automatically links to Google Fonts if specified here.
    text: Benton Sans # Keep if you have a way to serve it, otherwise use a Google Font like 'Open Sans' or 'Roboto'
    code: Fira Code
  palette:
    # Scheme 'slate' is a dark theme, 'default' is light.
    # We want a light base with crimson accents.
    - media: "(prefers-color-scheme: light)" # Default light theme
      scheme: default
      primary: red    # Material for MkDocs uses named colors. We'll override with CSS.
      accent: red     # Accent color for links/highlights.
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # Optional dark theme
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-on-outline
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - navigation.sections
    - toc.integrate
    - content.tooltips
    - content.footnotes
    - content.action.view # Allows users to view the raw Markdown source

extra_css:
  - css/wikistyle.css
  - https://fonts.googleapis.com/css2?family=Georgia&display=swap # Link to Georgia from Google Fonts

extra:
  favicon: iusm.ico
  version:
    provider: mike

nav:
  - Home: index.md
  - Applications: applications.md
  - Access: access.md
  - Branding Guidelines: branding_guidelines.md
  - Help: help.md
  - Newsletter Setup: Newsletterprep.md
  - Team: team.md

# Added Features #
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - attr_list
  - def_list
  - pymdownx.highlight # Necessary for code highlighting features
  - pymdownx.superfences # For advanced code blocks (like diagrams)
  - pymdownx.snippets # Useful for reusing content
  - pymdownx.details # For expandable sections
  - pymdownx.tabbed: # For content tabs
      alternate_style: true

plugins:
  - search
  - mike
  - minify: # Optional: Minify HTML, CSS, JS for faster loading
      minify_html: true
    