site_name: MD Student News
site_url: https://camshron.github.io/MDSNews

theme:
  name: material
  palette:
    scheme: default
    primary: custom
  features:
    - navigation.tabs
    - navigation.instant

nav:
  - Home: index.md
  - Applications: Applications.md
  - Branding Guidelines: Branding_Guidelines.md
  - Help: Help.md
  - Procedure: Procedure.md
  - Team: Team.md

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized


