# mkdocs.yml
site_name: MDSNews
site_url: https://camshron.github.io/mdsnews/ # Remember to replace 'your-username'

theme:
  name: material
  font:
    text: Benton Sans
    code: Fira Code
  palette:
    - scheme: default
      primary: red
      accent: red
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - navigation.sections
    - toc.integrate
    - content.tooltips
    - content.footnotes
    - content.action.view # Allows users to view the raw Markdown source

extra_css:
  - css/wikistyle.css
  - https://fonts.googleapis.com/css2?family=Georgia&display=swap # Link to Georgia from Google Fonts

extra:
  favicon: iusm.ico
  version:
    provider: mike

nav:
  - Home: index.md
  - Applications: applications.md
  - Access: access.md
  - Branding Guidelines: branding_guidelines.md
  - Help: help.md
  - Newsletter Setup: Newsletterprep.md
  - Team: team.md

# Added Features #
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - attr_list
  - def_list
  - pymdownx.highlight # Necessary for code highlighting features
  - pymdownx.superfences # For advanced code blocks (like diagrams)
  - pymdownx.snippets # Useful for reusing content
  - pymdownx.details # For expandable sections
  - pymdownx.tabbed: # For content tabs
      alternate_style: true

plugins:
  - search
  - mike
  - minify: # Optional: Minify HTML, CSS, JS for faster loading
      minify_html: true
    