site_name: MD Student News
site_url: https://camshron.github.io/MDSNews

theme:
  name: material
  palette:
    scheme: default
    primary: custom
  features:
    - navigation.tabs
  

extra_css:
  - stylesheets/wikistyle.css



  
