site_name: MDSNews 
site_url: https://your-username.github.io/mdsnews/
theme:
  name: material
  font:
    text: Benton Sans
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.instant

extra_css:
    - css/wikistyle.css

nav:
  - Home: index.md
  - Applications: applications.md
  - Access: access.md
  - Branding Guidelines: branding_guidelines.md
  - Help: help.md
  - Newsletter Setup: Newsletterprep.md
  - Team: team.md