site_name: MDSNews 
site_url: https://your-username.github.io/mdsnews/
theme:
  name: material
  font:
    text: Benton Sans
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.instant

nav:
  - Home: index.md
  - Applications: applications.md
  - Branding Guidelines: branding_guidelines.md
  - Help: help.md
  - Procedure: procedure.md
  - Team: team.md
