site_name: MD Student News
site_url: https://camshron.github.io/MDSNews

theme:
  name: material
  palette:
    scheme: default
    primary: custom
  features:
    - navigation.tabs

extra_css:
  - stylesheets/wikistyle.css

nav:
  - Home: index.md
  - Applications: Applications.md
  - Branding Guidelines: Branding & Guidelines.md
  - Help: Help.md
  - Procedure: Procedure.md
  - Team: Team.md

